/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeAnalyticsRouteImport } from './routes/time-analytics'
import { Route as StreaksRouteImport } from './routes/streaks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AiModeRouteImport } from './routes/ai-mode'
import { Route as IndexRouteImport } from './routes/index'

const TimeAnalyticsRoute = TimeAnalyticsRouteImport.update({
  id: '/time-analytics',
  path: '/time-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const StreaksRoute = StreaksRouteImport.update({
  id: '/streaks',
  path: '/streaks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AiModeRoute = AiModeRouteImport.update({
  id: '/ai-mode',
  path: '/ai-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-mode': typeof AiModeRoute
  '/settings': typeof SettingsRoute
  '/streaks': typeof StreaksRoute
  '/time-analytics': typeof TimeAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-mode': typeof AiModeRoute
  '/settings': typeof SettingsRoute
  '/streaks': typeof StreaksRoute
  '/time-analytics': typeof TimeAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-mode': typeof AiModeRoute
  '/settings': typeof SettingsRoute
  '/streaks': typeof StreaksRoute
  '/time-analytics': typeof TimeAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-mode' | '/settings' | '/streaks' | '/time-analytics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-mode' | '/settings' | '/streaks' | '/time-analytics'
  id:
    | '__root__'
    | '/'
    | '/ai-mode'
    | '/settings'
    | '/streaks'
    | '/time-analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiModeRoute: typeof AiModeRoute
  SettingsRoute: typeof SettingsRoute
  StreaksRoute: typeof StreaksRoute
  TimeAnalyticsRoute: typeof TimeAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time-analytics': {
      id: '/time-analytics'
      path: '/time-analytics'
      fullPath: '/time-analytics'
      preLoaderRoute: typeof TimeAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaks': {
      id: '/streaks'
      path: '/streaks'
      fullPath: '/streaks'
      preLoaderRoute: typeof StreaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-mode': {
      id: '/ai-mode'
      path: '/ai-mode'
      fullPath: '/ai-mode'
      preLoaderRoute: typeof AiModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiModeRoute: AiModeRoute,
  SettingsRoute: SettingsRoute,
  StreaksRoute: StreaksRoute,
  TimeAnalyticsRoute: TimeAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
